In [17]:
import torch
from torch import nn
from torch import optim
from torch.autograd import Variable

In [130]:
train_data = [("me gusta comer en la cafeteria".split(), "SPANISH"),
              ("Give it to me".split(), "ENGLISH"),
              ("No creo que sea una buena idea".split(), "SPANISH"),
              ("No it is not a good idea to get lost at sea".split(), "ENGLISH")]

test_data = [("Yo creo que si".split(), "SPANISH"),
             ("it is lost on me".split(), "ENGLISH"),
             ("jon jones is the greatest".split() , "ENGLISH"),
             ("Yo creo que si".split(), "SPANISH")]

In [118]:
#BOWClassifier Model
class BOWClassifier(nn.Module):

  def __init__(self, num_labels,vocab_size):
    super().__init__()
    self.layer_stack = nn.Sequential(
        nn.Linear(in_features= vocab_size , out_features = num_labels),
        nn.ReLU()
    )

  def forward(self , x):
    return self.layer_stack(x)

In [131]:
#make bag-of-words function
def make_bow(sentence , vocab):
  feature_vec = torch.zeros(len(vocab)) #intializing the count vector with zeros
  for word in sentence:
    feature_vec[vocab[word]] += 1
  return feature_vec.view(1,-1)

In [144]:
#labels of words into int or classes(0 or 1)
def make_labels(labels , label):
  return torch.LongTensor([labels[label]])

In [133]:
vocab = set()
corpus_list = train_data + test_data
for sent, _ in corpus_list:
  for word in sent:
    vocab.add(word)

In [134]:
vocab_map={word : key for key,word in enumerate(vocab)}

In [135]:
print(len(vocab))

30


In [146]:
VOCAB_SIZE = len(vocab)
NUM_LABELS = 2
labels = {"SPANISH" : 0, "ENGLISH" : 1}
model = BOWClassifier(NUM_LABELS, VOCAB_SIZE)
# loss_fn = nn.BCEWithLogitsLoss()
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(params = model.parameters() , lr = 0.01)

In [147]:
epochs = 100
for epoch in range(epochs):
  for data,label in train_data:
    model.train()
    feature_vec = Variable(make_bow(data,vocab_map))
    feature_vec.requires_grad = True
    target = Variable(make_labels(labels,label))
    model.zero_grad()
    output = model(feature_vec)
    # output_class = output.argmax(dim = 1)
    # output_class = output_class.type(torch.float64)
    # output_class.requires_grad = True
    print(output.shape , target.shape)
    # loss = loss_fn(output_class.type(torch.float64) , target.type(torch.float64))
    loss = loss_fn(output, target)
    loss.backward()
    optimizer.step()

torch.Size([1, 2]) torch.Size([1])
torch.Size([1, 2]) torch.Size([1])
torch.Size([1, 2]) torch.Size([1])
torch.Size([1, 2]) torch.Size([1])
torch.Size([1, 2]) torch.Size([1])
torch.Size([1, 2]) torch.Size([1])
torch.Size([1, 2]) torch.Size([1])
torch.Size([1, 2]) torch.Size([1])
torch.Size([1, 2]) torch.Size([1])
torch.Size([1, 2]) torch.Size([1])
torch.Size([1, 2]) torch.Size([1])
torch.Size([1, 2]) torch.Size([1])
torch.Size([1, 2]) torch.Size([1])
torch.Size([1, 2]) torch.Size([1])
torch.Size([1, 2]) torch.Size([1])
torch.Size([1, 2]) torch.Size([1])
torch.Size([1, 2]) torch.Size([1])
torch.Size([1, 2]) torch.Size([1])
torch.Size([1, 2]) torch.Size([1])
torch.Size([1, 2]) torch.Size([1])
torch.Size([1, 2]) torch.Size([1])
torch.Size([1, 2]) torch.Size([1])
torch.Size([1, 2]) torch.Size([1])
torch.Size([1, 2]) torch.Size([1])
torch.Size([1, 2]) torch.Size([1])
torch.Size([1, 2]) torch.Size([1])
torch.Size([1, 2]) torch.Size([1])
torch.Size([1, 2]) torch.Size([1])
torch.Size([1, 2]) t

In [148]:
for data, label in test_data:
  bow_vec = Variable(make_bow(data, vocab_map))
  output = model(bow_vec)
  print(output.argmax(dim = 1))#predictions

tensor([0])
tensor([1])
tensor([1])
tensor([0])


In [139]:

data = ("me gusta comer en la cafeteria".split(), "SPANISH")
# vec = make_bow(data[0] , vocab_map)
target = make_labels(labels, data[1])

In [140]:
# vec.shape
target.shape

torch.Size([1])

In [71]:
torch.Tensor([[3,1]]).argmax(dim = 1)

tensor([0])